# BASE
class InvariantViolation(RuntimeError):...

# MODELS
class InvalidBar(InvariantViolation):...
class InvaliRawTick(InvariantViolation):...

# MARKET STORE
class EventOrderingViolation(InvariantViolation):...
class MarketViewIsEmpty(InvariantViolation):...
class NoMarketDataProcessed(InvariantViolation):...

# FEATURE STORE
class FeatureEmpty(InvariantViolation):...
class FeatureNotReady(InvariantViolation):...