# BASE
class InsufficientHistoryError(Exception):...

class InvalidTrade(Exception):...
class InvalidOrderType(Exception):...

class UnknownSymbolError(Exception):...

# FEATURES
class MissingFeatureRequirementError(Exception):...
class FeatureTypeMismatchError(Exception):...